name: Deploy to AWS

on:
  push:
    branches:
      - main   # triggers when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Get Code from GitHub
        uses: actions/checkout@v3

      - name: 2. Install Dependencies
        run: npm install

      - name: 3. Build Project
        run: npm run build

      - name: 4. Upload to AWS Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/html/TV_Screens/Demo"

      - name: 5. Restart Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart nginx