name: Deploy to AWS

on:
  push:
    branches:
      - main   # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install Dependencies
      - name: Install Dependencies
        run: npm install

      # 3. Build Project
      - name: Build Project
        run: npm run build

      # 4. Clean OLD files (VERY IMPORTANT)
      - name: Clean old files on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            rm -rf /var/www/html/TV_Screens/Demo/*

      # 5. Upload NEW build files
      - name: Upload to AWS Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "dist/*"
          target: "/var/www/html/TV_Screens/Demo"
          overwrite: true

      # 6. Restart Nginx
      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart nginx