name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install
      - name: Install Dependencies
        run: npm install

      # 3. Build
      - name: Build Project
        run: npm run build

      # 4. Clean ONLY Demo folder
      - name: Clean Demo folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf /var/www/html/TV_Screens/Demo/*
            mkdir -p /var/www/html/TV_Screens/Demo

      # 5. Upload ONLY dist contents (NO nested folder)
      - name: Upload build files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/html/TV_Screens/Demo"
          overwrite: true
          strip_components: 1

      # 6. Fix permissions (IMPORTANT for 500 error)
      - name: Fix permissions
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/html/TV_Screens/Demo
            sudo chmod -R 755 /var/www/html/TV_Screens/Demo

      # 7. Restart nginx
      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
